# Generated by Django 5.0.7 on 2024-08-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_verified',
            new_name='phone_verified',
        ),
    ]
